# Generated by Django 3.1.3 on 2021-03-18 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0002_auto_20210317_1356'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='回复时间'),
        ),
        migrations.AlterField(
            model_name='post',
            name='updated_at',
            field=models.DateTimeField(null=True, verbose_name='更新时间'),
        ),
        migrations.AlterField(
            model_name='topic',
            name='last_update',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
